const subjects = [{text:"You should", punctuation:".", posessive:"your"}, {text:"I should", punctuation:".", posessive:"my"}, {text:"You will", punctuation:".", posessive:"your"}, {text:"I will", punctuation:".", posessive: "my"}, {text:"They will", punctuation:".", posessive:"their"}, {text:"Somebody once told me the world was gonna", punctuation:".", posessive:"my"}, {text:"The French will", punctuation:".", posessive:"their"}, {text:"Silicon Valley might", punctuation:".", posessive:"its"}, {text:"Someday, people will", punctuation:".", posessive:"their"}, {text:"Never gonna", punctuation:".", posessive:"your"}, {text:"Someday, we'll", punctuation:".", posessive:"our"}, {text:"The People's Republic of China will likely", punctuation:".", posessive:"their"}, {text:"Mariah Cary will soon", punctuation:".", posessive:"her"}, {text:"Your mother will", punctuation:".",posessive:"her"}, {text:"I don't like tacos. They make me", punctuation:".", posessive:"my"}, {text:"MINIONS!!! Tonight we will", punctuation:"!!!", posessive:"our"}, {text:"Elon Musk will create a company that will", punctuation:".", posessive:"his"}, {text:"Somewhere in the Amazon, a piranha will", punctuation:".", posessive:"its"}, {text:"Disney's next hit movie will feature a child that decides to", punctuation:".", posessive:"their"}, "Taylor Swift has just released a song about how her ex used to", "If we need, we can", "If possible, we will", "The President of the United States has announced a four-year plan to", "The leaders of the United Nations have decided to ", "If you aren't careful, you might", "A random cow will", "Your next-door neighbor will", "The winner of this year's Super Bowl is expected to", "A random Lichtensteinian teen will soon", "Kendrick Lamar's latest diss track is about how Drake used to", "Geese are genetically predisposed to", "In fifteen minutes, you could", "The next iOS update will give users the ability to", "Some Chevrolet vehicles are being recalled, as they could possibly", "If we don't regulate AI, it will", "In the next 100 years, humanity will", "Jeff Bezos really shouldn't", "The Royal Family is expected to", "I remember that one time I decided to", "Some are against it, but I am in favor of the new bipartisan bill that will", "Your left shoelace will", "People should", "The Alabama Department of Education now requires that schools teach all students how to", "This new app lets you", "The CIA would never"]
const actions = ["start a fire.", "call your mom.", "learn a language on Duolingo.", "play a game.", "try to take over the world.", "roll me.", "give you up.", "find it.", "adopt a penguin.", "move to North Korea.", "start a society of penguins.", "commit tax fraud.", "assassinate Daniel Radcliffe.", "achieve unaided human flight.", "dive into a vat of flamingos.", "listen to Lesser Minds podcast on Spotify.", "steal the moon!!!", "reintroduce dinosaurs to Yellowstone.", "run DOOM on a 40-year old digital alarm clock.", "send tactical airstrike giraffes.", "take this.", "contemplate the meaning of life.", "eliminate all opponents.", "disengage your ribcage.", "fall off a treadmill.", "enter an infinite loop.", "clean out your room.", "eat 150 lbs. of pancakes.", "run for President of the United States.", "invade the Republic of the Congo.", "launch a military campaign that will expand the country of Chad's territory by 2,984%.", "program a random sentence generator.", "give shoutouts to the entire population of Earth on Facebook Live.", "start a small buisiness.", "build a potato-powered quantum computer.", "recreate your hometown in Animal Crossing.", "discover 47 new elements.", "legalize marinara.", "run a marathon with one leg and a baguette.", "refrain from stealing a baguette from Panera.", "found a bank that just steals people's money.", "sell NFTs.", "release Windows 12.", "set an Olympic record for slowest 100m dash.", "save fifteen percent or more on car insurance.", "stage a coup.", "purchase a Mac that runs Windows on the black market.", "throw a syntax error on line -1.", "build a guitar out of LEGO hands.", "learn to draw.", "not make sense, and instead make dollars."]
const commentary = ["That sounds fun.", "This message is endorsed by The Committee to Elect Ryan Reynolds.", "I support that.", "It might be risky.", "I ain't the sharpest tool in the shed.", "Never gonna let you down.", "The Rainbow Connection.", "RUN FOR YOUR LIVES!!!", "My resolution? Airstrikes.", "Yep yep yep!", "That doesn't sound boring at all.", "It's dangerous to go alone.", "I just hope nothing explodes.", "It will be done with minimal explosions.", "That's a real knee-slapper, isn't it.", "That's why I have decided to run for President of the United States.", "That's why, effective immediately, all citizens will be issued emotional support dogs.", "Batteries not included.", "That's why I don't trust geese.", "I want a 2,500 word essay on that, it's due next friday.", "Say that five times fast.", "Soon.", "Help, I'm trapped in a random sentence generator!", "You may be entitled to compenstation.", "We're in for it now.", "We're all doomed!", "This could be good.", "It might even work!", "That is, unless Russia does it first.", "Then, I can finally sleep at night.", "Hopefully no one gets hurt.", "Think of the possibilities!", "And that's final.", "I scheduled it for tomorrow at 1:67.", "That's a good thing, right?", "-Benjamin Franklin", "Beep Boop", "If I could just figure out how...", "It shouldn't be fatal.", "Ya heard?", "We just need to keep an eye out for any suspicious-looking hippos.", "It might take a couple tries, though.", "You're not allergic to Zambonis, right?", "Are you with me?", "What could go wrong?", "But you didn't hear that from me.", "Right, old sport?", "I don't know how that's even possible."]
let element = document.querySelector('button');
const generateSentence = () => {
  const subject = subjects[Math.floor(Math.random() * (subjects.length))]
  const action = actions[Math.floor(Math.random() * (actions.length))]
  const comment = commentary[Math.floor(Math.random() * (commentary.length))]
  document.getElementById('output').innerHTML = subject + ' ' + action + ' ' + comment
  console.log('There are ' + (subjects.length * actions.length * commentary.length) + ' possible outputs at this time.')
}

generate.onclick = generateSentence;