export const actions = [
  "start a fire",
  "call POSESSIVE mom",
  "learn a language on Duolingo",
  "play a game",
  "try to take over the world",
  "roll me",
  "give you up",
  "find it",
  "adopt a penguin",
  "move to North Korea",
  "start a society of penguins",
  "commit tax fraud",
  "assassinate Daniel Radcliffe",
  "achieve unaided human flight",
  "dive into a vat of flamingos",
  "listen to Lesser Minds podcast on Spotify",
  "steal the moon",
  "reintroduce dinosaurs to Yellowstone",
  "run DOOM on a 40-year old digital alarm clock",
  "send tactical airstrike giraffes",
  "take this",
  "contemplate the meaning of life",
  "eliminate all opponents",
  "disengage POSESSIVE ribcage",
  "fall off a treadmill",
  "enter an infinite loop",
  "clean out POSESSIVE room",
  "eat 3 times POSESSIVE body weight in pancakes",
  "run for President of the United States",
  "invade the Republic of the Congo",
  "launch a military campaign that will expand the country of Chad's territory by 2,984%",
  "program a random sentence generator",
  "give shoutouts to the entire population of Earth on Facebook Live",
  "start a small buisiness",
  "build a potato-powered quantum computer",
  "recreate POSESSIVE hometown in Animal Crossing",
  "discover 47 new elements",
  "legalize marinara",
  "run a marathon with one leg and a baguette",
  "refrain from stealing a baguette from Panera",
  "found a bank that just steals people's money",
  "sell NFTs",
  "release Windows 12",
  "set an Olympic record for slowest 100m dash",
  "save fifteen percent or more on car insurance",
  "stage a coup",
  "purchase a Mac that runs Windows on the black market",
  "throw a syntax error on line -1",
  "build a guitar out of LEGO hands",
  "learn to draw", 
  "not make sense, and instead make dollars",
  "thouroughly read the Disney+ Terms and Conditions",
  "learn to play an instrument",
  "plug a ukelele into a guitar amp",
  "slip on the salt that they put on ice to keep you from slipping",
  "try to imagine a new color",
  "remind the person reading this about breathing so they have to conciously think about doing it",
  "raise a group of mutant turtles as ninjas",
  "buy out Youtube just to make it have less ads",
  "one-up Boeing by NOT stranding two astronauts on the International Space Station",
  "git commit -am 'Oh wait, this isn't the terminal'",
  "make meta jokes about Meta",
  "remind people that the X logo is just a unicode character and can't be copyrighted, but can be typed(Here, copy-and-paste it: 𝕏)",
  "attend clown school",
  "score a 37 on the ACT",
  "get some fuzzy slippers",
  "send a spaceship to the sun, but at night so it doesn't burn up",
  "score a huge NIL deal despite not being a college athlete",
  "successfully rickroll a teacher in an assignment",
  "play the Chick-fil-a jingle on saxaphone",
  "play wheelchair soccer",
  "vandalize the Wikipedia article on Wikipedia vandalism",
  "be arrested on 34 counts of buisiness fraud",
  "create two websites that literally only redirect back and forth to each other"
]