export const commentary = [
  "That sounds fun.",
  "This message is endorsed by The Committee to Elect Ryan Reynolds.",
  "I support that.",
  "It might be risky.",
  "I ain't the sharpest tool in the shed.",
  "Never gonna let you down.",
  "The Rainbow Connection.",
  "RUN FOR YOUR LIVES!!!",
  "My resolution? Airstrikes.",
  "Yep yep yep!",
  "That doesn't sound boring at all.",
  "It's dangerous to go alone.",
  "I just hope nothing explodes.",
  "It will be done with minimal explosions.",
  "That's a real knee-slapper, isn't it.",
  "That's why I have decided to run for President of the United States.",
  "That's why, effective immediately, all citizens will be issued emotional support dogs.",
  "Batteries not included.",
  "That's why I don't trust geese.",
  "I want a 2,500 word essay on that, it's due next friday.",
  "Say that five times fast.",
  "Soon.",
  "Help, I'm trapped in a random sentence generator!",
  "You may be entitled to compenstation.",
  "We're in for it now.",
  "We're all doomed!",
  "This could be good.",
  "It might even work!",
  "That is, unless Russia does it first.",
  "Then, I can finally sleep at night.",
  "Hopefully no one gets hurt.",
 "Think of the possibilities!",
  "And that's final.",
  "I scheduled it for tomorrow at 1:67.",
  "That's a good thing, right?",
  "-Benjamin Franklin",
  "Beep Boop",
  "If I could just figure out how...",
  "It shouldn't be fatal.",
  "Ya heard?",
  "We just need to keep an eye out for any suspicious-looking hippos.",
  "It might take a couple tries, though.",
  "You're not allergic to Zambonis, right?",
  "Are you with me?",
  "What could go wrong?",
  "But you didn't hear that from me.",
  "Right, old sport?",
  "I don't know how that's even possible."
]