export const subjects = [
  {text:"You should", punctuation:".", posessive:"your"},
  {text:"I should", punctuation:".", posessive:"my"},
  {text:"You will", punctuation:".", posessive:"your"},
  {text:"I will", punctuation:".", posessive: "my"},
  {text:"They will", punctuation:".", posessive:"their"},
  {text:"Somebody once told me the world was gonna", punctuation:".", posessive:"my"},
  {text:"The French will", punctuation:".", posessive:"their"},
  {text:"Silicon Valley might", punctuation:".", posessive:"its"},
  {text:"Someday, people will", punctuation:".", posessive:"their"},
  {text:"Never gonna", punctuation:".", posessive:"your"},
  {text:"Someday, we'll", punctuation:".", posessive:"our"},
  {text:"The People's Republic of China will likely", punctuation:".", posessive:"their"},
  {text:"Mariah Cary will soon", punctuation:".", posessive:"her"},
  {text:"Your mother will", punctuation:".",posessive:"her"},
  {text:"I don't like tacos. They make me", punctuation:".", posessive:"my"},
  {text:"MINIONS!!! Tonight we will", punctuation:"!!!", posessive:"our"},
  {text:"Elon Musk will create a company that will", punctuation:".", posessive:"his"},
  {text:"Somewhere in the Amazon, a piranha will", punctuation:".", posessive:"its"},
  {text:"Disney's next hit movie will feature a child that decides to", punctuation:".", posessive:"their"},
  {text:"Taylor Swift has just released a song about how her ex used to", punctuation:".", posessive:"his"},
  {text:"If we need, we can", punctuation:".", posessive:"our"},
  {text:"If possible, we will", punctuation:".", posessive:"our"},
  {text:"The President of the United States has announced a four-year plan to", punctuation:".", posessive:"our nation's"},
  {text:"The leaders of the United Nations have decided to", punctuation:".", posessive:"the world's"},
  {text:"If you aren't careful, you might", punctuation:".", posessive:"your"},
  {text:"A random cow will", punctuation:".", posessive:"its"},
  {text:"Your next-door neighbor will", punctuation:".", posessive:"their"},
  {text:"The winner of this year's Super Bowl is expected to", punctuation:".", posessive:"their"},
  {text:"A random Lichtensteinian teen will soon", punctuation:".", posessive:"their"},
  {text:"Kendrick Lamar's latest diss track is about how Drake used to", punctuation:".", posessive:"his"},
  {text:"Geese are genetically predisposed to", punctuation:".", posessive:"their"},
  {text:"In fifteen minutes, you could", punctuation:".", posessive:"your"},
  {text:"The next iOS update will give users the ability to", punctuation:".", posessive:"their"},
  {text:"Some Chevrolet vehicles are being recalled, as they could possibly", punctuation:".", posessive:"their"},
  {text:"If we don't regulate AI, it will", punctuation:".", posessive:"its"},
  {text:"In the next 100 years, humanity will", punctuation:".", posessive:"its"},
  {text:"Jeff Bezos really shouldn't", punctuation:".", posessive:"his"},
  {text:"The Royal Family is expected to", punctuation:".", posessive:"their"},
  {text:"I remember that one time I decided to", punctuation:"...", posessive:"my"},
  {text:"Some are against it, but I am in favor of the new bipartisan bill that will", punctuation:".", posessive:"our nation's"},
  {text:"Your left shoelace will", punctuation:".", posessive:"your"},
  {text:"People should", punctuation:".", posessive:"their"},
  {text:"The Alabama Department of Education now requires that schools teach all students how to", punctuation:".", posessive:"their"},
  {text:"This new app lets you", punctuation:".", posessive:"your"},
  {text:"The CIA would never", punctuation:".", posessive:"our"},
  {text:"Is it even possible to", punctuation:"?", posessive:"one's"},
  {text:"What would happen if we were to", punctuation:"?", posessive:"our"},
  {text:"Who do you think will be the first person to", punctuation:"?", posessive:"their"},
  {text:"Look, you're the one who decided it was a good idea to", punctuation:"!", posessive:"your"},
  {text:"How many years does it take off your life if you", punctuation:"?", posessive:"your"},
  {text:"Who would've thought that all it took to disrupt an ecosystem was to", punctuation:"?", posessive:"its"},
  {text:"Nobody expected the IOC to take away Jordan Chile's medal. All she did was", punctuation:".", posessive:"her"}
]