export const subjects = [
  {text:"You should", punctuation:".", posessive:"your"},
  {text:"I should", punctuation:".", posessive:"my"},
  {text:"You will", punctuation:".", posessive:"your"},
  {text:"I will", punctuation:".", posessive: "my"},
  {text:"They will", punctuation:".", posessive:"their"},
  {text:"Somebody once told me the world was gonna", punctuation:".", posessive:"my"},
  {text:"The French will", punctuation:".", posessive:"their"},
  {text:"Silicon Valley might", punctuation:".", posessive:"its"},
  {text:"Someday, people will", punctuation:".", posessive:"their"},
  {text:"Never gonna", punctuation:".", posessive:"your"},
  {text:"Someday, we'll", punctuation:".", posessive:"our"},
  {text:"The People's Republic of China will likely", punctuation:".", posessive:"their"},
  {text:"Mariah Cary will soon", punctuation:".", posessive:"her"},
  {text:"Your mother will", punctuation:".",posessive:"her"},
  {text:"I don't like tacos. They make me", punctuation:".", posessive:"my"},
  {text:"MINIONS!!! Tonight we will", punctuation:"!!!", posessive:"our"},
  {text:"Elon Musk will create a company that will", punctuation:".", posessive:"his"},
  {text:"Somewhere in the Amazon, a piranha will", punctuation:".", posessive:"its"},
  {text:"Disney's next hit movie will feature a child that decides to", punctuation:".", posessive:"their"},
  {text:"Taylor Swift has just released a song about how her ex used to", punctuation:".", posessive:"his"},
  {text:"If we need, we can", punctuation:".", posessive:"our"},
  {text:"If possible, we will", punctuation:".", posessive:"our"},
  {text:"The President of the United States has announced a four-year plan to", punctuation:".", posessive:"our nation's"},
  {text:"The leaders of the United Nations have decided to", punctuation:".", posessive:"the world's"},
  {text:"If you aren't careful, you might", punctuation:".", posessive:"your"},
  {text:"A random cow will", punctuation:".", posessive:"its"},
  {text:"Your next-door neighbor will", punctuation:".", posessive:"their"},
  {text:"The winner of this year's Super Bowl is expected to", punctuation:".", posessive:"their"},
  {text:"A random Lichtensteinian teen will soon", punctuation:".", posessive:"their"},
  {text:"Kendrick Lamar's latest diss track is about how Drake used to", punctuation:".", posessive:"his"},
  {text:"Geese are genetically predisposed to", punctuation:".", posessive:"their"},
  {text:"In fifteen minutes, you could", punctuation:".", posessive:"your"},
  {text:"The next iOS update will give users the ability to", punctuation:".", posessive:"their"},
  {text:"Some Chevrolet vehicles are being recalled, as they could possibly", punctuation:".", posessive:"their"},
  {text:"If we don't regulate AI, it will", punctuation:".", posessive:"its"},
  {text:"In the next 100 years, humanity will", punctuation:".", posessive:"its"},
  {text:"Jeff Bezos really shouldn't", punctuation:".", posessive:"his"},
  {text:"The Royal Family is expected to", punctuation:".", posessive:"their"},
  {text:"I remember that one time I decided to", punctuation:"...", posessive:"my"},
  {text:"Some are against it, but I am in favor of the new bipartisan bill that will", punctuation:".", posessive:"our nation's"},
  {text:"Your left shoelace will", punctuation:".", posessive:"your"},
  {text:"People should", punctuation:".", posessive:"their"},
  {text:"The Alabama Department of Education now requires that schools teach all students how to", punctuation:".", posessive:"their"},
  {text:"This new app lets you", punctuation:".", posessive:"your"},
  {text:"The CIA would never", punctuation:".", posessive:"our"},
  {text:"Is it even possible to", punctuation:"?", posessive:"one's"},
  {text:"What would happen if we were to", punctuation:"?", posessive:"our"},
  {text:"Who do you think will be the first person to", punctuation:"?", posessive:"their"},
  {text:"Look, you're the one who decided it was a good idea to", punctuation:"!", posessive:"your"},
  {text:"How many years does it take off your life if you", punctuation:"?", posessive:"your"},
  {text:"Who would've thought that all it took to disrupt an ecosystem was to", punctuation:"?", posessive:"its"},
  {text:"Nobody expected the IOC to take away Jordan Chile's medal. All she did was", punctuation:".", posessive:"her"},
  {text:"\"Yes, Mrs. Jones. Little Jimmy said he was going to, and I quote, '", punctuation:"'.\"", posessive:"another child's"},
  {text:"Remember, only you can", punctuation:".", posessive:"someone's"},
  {text:"Everyone was shocked when the FBI raid on Disney World revealed a secret plot to", punctuation:".", posessive:"the company's"},
  {text:"There's apparently a rather lengthly Wikipedia article on people who decided to", punctuation:".", posessive:"their"},
  {text:"I wouldn't even be surprised if Jack Black were to", punctuation:".", posessive:"his"},
  {text:"Would you rather owe someone a million dollars or", punctuation:"?", posessive:"your"},
  {text:"Would you rather win a million dollars or", punctuation:"?", posessive:"your"},
  {text:"My dog tried to", punctuation:".", posessive:"my"},
  {text:"John Bongiovi will", punctuation:".", posessive:"his"},
  {text:"Supposedly, Lebron James has a tendency to", punctuation:".", posessive:"his"},
  {text:"The Dutch Philharmonic Orchestra is going to", punctuation:".", posessive:"their"},
  {text:"Apparently it's illegal in the state of Nevada to", punctuation:".", posessive:"your"},
  {text:"RFK Jr.'s campaign has announced that he will", punctuation:".", posessive:"his"},
  {text:"A sentient Tesla will", punctuation:".", posessive:"its"},
  {text:"Napoleon(either Bonaparte or Dynamite) will", punctuation:".", posessive:"his"},
  {text:"Look out! They're going to", punctuation:"!", posessive:"your"},
  {text:"You", punctuation:".", posessive:"your"},
  {text:"Why would you", punctuation:"?", posessive:"your"},
  {text:"Who would want to", punctuation:"?", posessive:"their"},
  {text:"Nobody could have predicted that they were going to", punctuation:".", posessive:"their"},
  {text:"For my next trick, I will", punctuation:"!", posessive:"your"},
  {text:"George Clooney might", punctuation:".", posessive:"his"},
  {text:"Rihanna is going to", punctuation:".", posessive:"her"},
  {text:"Will Smith will slap anyone who dares to", punctuation:".", posessive:"his"},
  {text:"Look, I HAD to", punctuation:"!", posessive:"my"},
  {text:"They say that if you", punctuation:" on a clear night, you can see the ghost of Robin Williams.", posessive:"your"},
  {text:"Trying to burn some calories? Just", punctuation:"!", posessive:"your"},
  {text:"National Treasure 3 still hasn't been made because the writers can't agree on whether or not the villain should", punctuation:".", posessive:"their"},
  {text:"Nicholas Cage should", punctuation:".", posessive:"his"},
  {text:"No, of course I wouldn't", punctuation:"!", posessive:"your"},
  {text:"Tom Felton has recently been arrested for attempting to", punctuation:".", posessive:"his"},
  {text:"PETA has started a campaign to convince people not to", punctuation:".", posessive:"their"},
  {text:"Weird Al could", punctuation:" and nobody would even be surprised.", posessive:"somebody's"},
  {text:"Miley Cyrus will", punctuation:".", posessive:"her"},
  {text:"Zach Bryan will", punctuation:".", posessive:"his"},
  {text:"Bruno Mars would", punctuation:" for you.", posessive:"your"},
  {text:"It would be so brat to", punctuation:".", posessive:"your"},
  {text:"You know what they say.", punctuation:" or go home.", posessive:"your"},
  {text:"If you can't beat 'em", punctuation:".", posessive:"their"},
  {text:"We might as well", punctuation:".", posessive:"our"},
  {text:"Which member of the FRIENDS cast is most likely to", punctuation:"?", posessive:"their"},
  {text:"Should I", punctuation:"?", posessive:"my"},
  {text:"I remember when we would", punctuation:".", posessive:"our"},
  {text:"People just don't", punctuation:" anymore.", posessive:"their"},
  {text:`How do you say "I'm going to`, punctuation:`" in Spanish?`, posessive:"my"},
  {text:"Hey, we should", punctuation:".", posessive:"our"},
  {text:"The entire country of Belgium wants to", punctuation:".", posessive:"their"},
  {text:"I want to", punctuation:".", posessive:"my"}
]